# Generated by Django 3.2.7 on 2021-09-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suit', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=4)),
                ('symbol', models.ImageField(default='default.jpg', upload_to='avatars')),
            ],
        ),
    ]
