# Generated by Django 3.2.7 on 2021-09-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tile',
            name='value',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
