# Generated by Django 3.2.7 on 2021-09-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_game_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='face_down',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='game',
            name='face_up',
            field=models.JSONField(default=[]),
        ),
    ]
