# Generated by Django 3.2.7 on 2021-09-21 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0004_auto_20210921_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.JSONField(null=True),
        ),
    ]
