# Generated by Django 3.2.7 on 2021-09-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0006_player_current_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tile',
            name='symbol',
            field=models.CharField(max_length=20),
        ),
    ]
